/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Jp9kR9WcNuc
 */

import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Header() {
  return (
    <header
      key="1"
      className="flex items-center justify-between p-4 border-b border-gray-200"
    >
      <Link className="flex items-center" href="#">
        <CrownIcon className="w-6 h-6 mr-2" />
        <h1 className="text-2xl font-bold">Chalk Checker</h1>
      </Link>
      <nav className="flex items-center space-x-4">
        <Link className="text-lg font-medium hover:underline" href="#">
          Trends
        </Link>
        <Link className="text-lg font-medium hover:underline" href="#">
          About
        </Link>
        <Button variant="outline">Login</Button>
        <Button>Sign Up</Button>
      </nav>
    </header>
  )
}


function CrownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m2 4 3 12h14l3-12-6 7-4-7-4 7-6-7zm3 16h14" />
    </svg>
  )
}
