/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5YDWmkMZ5JW
 */
import { Input } from "@/components/ui/input"
import { Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function MainSearch() {
  return (
    <section key="1" className="w-full max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-10">

      <div className="w-full mb-6">
        <div className="relative">
          <Input
            className="w-full pl-10 pr-4 py-2 rounded-md border focus:outline-none focus:border-blue-500"
            placeholder="Search here..."
            type="text"
          />
          <SearchIcon className="absolute left-0 ml-3 my-2 w-5 h-5 text-gray-500" />
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6">
        <Card className="bg-white rounded shadow-sm p-5">
          <CardHeader className="flex items-center">
            <Avatar className="mr-4" src="/placeholder.svg?height=40&width=40" />
            <h2 className="text-xl font-semibold">Object 1 and Object 2</h2>
          </CardHeader>
          <CardContent>
            <p className="text-gray-600">Description for Object 1 and Object 2</p>
            <Link className="text-blue-500" href="#">
              View More
            </Link>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 gap-6 mt-6">
        <Card className="bg-white rounded shadow-sm p-5">
          <CardHeader className="flex items-center">
            <Avatar className="mr-4" src="/placeholder.svg?height=40&width=40" />
            <h2 className="text-xl font-semibold">Object 3</h2>
          </CardHeader>

          <CardContent>
            <p className="text-gray-600">This will be a list of players to select from.</p>
            <Link className="text-blue-500" href="#">
              View More
            </Link>
          </CardContent>

        </Card>
      </div>
    </section>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
